/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  safelist: [
    'py-section', 'pt-hero-top', 'pb-hero-bottom', 'gap-hero-gap',
    'py-cta-block', 'px-card', 'p-card', 'pt-cta-gap', 'gap-cta-gap',
    'gap-column', 'gap-title-content', 'mt-title-content', 'gap-block', 'mt-block', 'pt-block',
    'gap-card-gap', 'gap-faq',
    'py-s2', 'py-s2_5', 'py-s6', 'gap-s1', 'gap-s2', 'gap-s3', 'gap-s4', 'mt-s1', 'mt-s2', 'mt-s3', 'mb-s10', 'pt-s3', 'pb-s2', 'pb-s3', '-mt-s1',
    'px-s2', 'scroll-pl-s2', 'scroll-pr-s2',
  ],
  theme: {
    extend: {
      colors: {
        surface: 'var(--color-surface)',
        'surface-muted': 'var(--color-surface-muted)',
        'surface-subtle': 'var(--color-surface-subtle)',
        'surface-dark': 'var(--color-surface-dark)',
        text: 'var(--color-text)',
        'text-muted': 'var(--color-text-muted)',
        'text-inverse': 'var(--color-text-inverse)',
        'text-muted-inverse': 'var(--color-text-muted-inverse)',
        accent: 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        'accent-brand': 'var(--color-accent-brand)',
        'accent-brand-hover': 'var(--color-accent-brand-hover)',
        border: 'var(--color-border)',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        display: ['clamp(2rem, 5vw, 2.5rem)', { lineHeight: '1.2' }],
        h1: ['2.25rem', { lineHeight: '1.2' }],
        h2: ['1.75rem', { lineHeight: '1.28' }],
        h3: ['1.25rem', { lineHeight: '1.4' }],
        body: ['1rem', { lineHeight: '1.6' }],
        small: ['0.875rem', { lineHeight: '1.5' }],
      },
      maxWidth: {
        container: 'var(--container-max)',
        content: 'var(--content-max)',
        'media-col': 'var(--media-col-max)',
      },
      spacing: {
        's1': 'var(--space-1)',
        's2': 'var(--space-2)',
        's3': 'var(--space-3)',
        's4': 'var(--space-4)',
        's6': 'var(--space-6)',
        's8': 'var(--space-8)',
        's12': 'var(--space-12)',
        's15': 'var(--space-15)',
        's2_5': 'var(--space-2_5)',
        's9': 'var(--space-9)',
        's10': 'var(--space-10)',
        's11': 'var(--space-11)',
        'section': 'var(--section-padding-y)',
        'hero-top': 'var(--hero-padding-top)',
        'hero-bottom': 'var(--hero-padding-bottom)',
        'hero-gap': 'var(--hero-inner-gap)',
        'cta-block': 'var(--cta-block-padding-y)',
        'cta-gap': 'var(--cta-inner-gap)',
        'column': 'var(--column-gap)',
        'title-content': 'var(--title-to-content)',
        'block': 'var(--block-gap)',
        'faq': 'var(--faq-item-gap)',
        'card': 'var(--card-padding)',
        'card-gap': 'var(--card-gap)',
        'content': 'var(--title-to-content)',
        'cta': 'var(--cta-inner-gap)',
      },
      borderRadius: {
        'soft': 'var(--radius-soft)',
        'card': 'var(--radius-card)',
      },
    },
  },
  plugins: [],
};
